In [1]:
import torch

In [3]:
# tensor: fundamental building block

# direct creation from data
data = [[1, 2, 3], [4, 5, 6]]
my_tensor = torch.tensor(data)

print(my_tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
# creation from a desired shape
# useful when the shape is known, but the values are not 

shape = (2, 3)

ones = torch.ones(shape)
zeros = torch.zeros(shape)
random = torch.randn(shape)

print(random)

tensor([[-1.3872,  0.3676, -0.2538],
        [ 0.5073,  0.5208, -1.3946]])


In [6]:
# creation by mimicking another tensor
# useful when a tensor with the same shape and type as another one is needed

template = torch.tensor([[1, 2], [3, 4]])

rand_like = torch.randn_like(template, dtype=torch.float)

print(f'Template tensor:\n {template}\n')
print(f'Randn_like tensor:\n {rand_like}\n')

Template tensor:
 tensor([[1, 2],
        [3, 4]])

Randn_like tensor:
 tensor([[ 0.1776, -0.8930],
        [-1.3354,  0.0304]])



In [ ]:
# inside a tensor: shape, type and device

tensor = torch.randn(shape)

print(f'Shape: {tensor.shape}')  # touple describing the dimensions
print(f'Datatype: {tensor.dtype}')  # data type, default is float32
print(f'Device: {tensor.device}')  # where the tensor lives: cpu or gpu

Shape: torch.Size([2, 3])
Datatype: torch.float32
Device: cpu


In [8]:
# by default, a tensor is just data
# to tell Pytorch that a tensor is a learnable parameter: requires_grad = True

x_data = torch.tensor([[1., 2.], [3., 4,]])  # standard data tensor
w = torch.tensor([[1.0], [2.0]], requires_grad=True)  # parameter tensor

print(f'Data tensor requires_grad: {x_data.requires_grad}')
print(f'Parameter tensor requires_grad: {w.requires_grad}')

Data tensor requires_grad: False
Parameter tensor requires_grad: True


In [9]:
# building a graph through operations

a = torch.tensor(2., requires_grad=True)
b = torch.tensor(3., requires_grad=True)
x = torch.tensor(4., requires_grad=True)

y = a + b
z = x * y

print(z)

tensor(20., grad_fn=<MulBackward0>)


In [ ]:
# every tensor created by an operation has the special attribute .grad_fn
# Pytorch builds a graph by registering the operations through this attribute

print(a.grad_fn)  # created by the user, not by an operation
print(y.grad_fn)  # created by addition
print(z.grad_fn)  # created by multiplication

None


In [15]:
# operations

a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[10, 20], [30, 40]])
print(f'a = {a}\n')
print(f'b = {b}\n')

# * multiplies matching positions (the tensors must have the same shape)
print(f'a * b = {a * b}\n')

# @ matrix multiplication (number of cols of 1st matrix must match rows of 2nd matrix)
print(f'a @ b = {a @ b}')

a = tensor([[1, 2],
        [3, 4]])

b = tensor([[10, 20],
        [30, 40]])

a * b = tensor([[ 10,  40],
        [ 90, 160]])

a @ b = tensor([[ 70, 100],
        [150, 220]])


**When building a linear layer, always use the `@` operator.**

In [16]:
# reduction operations: reduce a tensor to a smaller number of elements
# e.g. sum, mean, max

scores = torch.tensor([[10., 20., 30.], [5., 10., 15.]])

print(f'Overall mean: {scores.mean()}')

Overall mean: 15.0


In [18]:
# the dim argument lets us control which direction to collapse
# for 2D tensors:
# dim = 0 collapses the rows (operates vertically)
# dim = 1 collapses the columns (operates horizontally)

print(f'Col means: {scores.mean(dim=0)}')
print(f'Row means: {scores.mean(dim=1)}')

Col means: tensor([ 7.5000, 15.0000, 22.5000])
Row means: tensor([20., 10.])


In [20]:
# indexing (same as numpy)

x = torch.arange(12).reshape(3, 4)
col_2 = x[:, 2]

print(f'x = {x}')
print(f'Column 2: {col_2}')


x = tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
Column 2: tensor([ 2,  6, 10])


In [22]:
# argmax: finds the index of the highest value
# this is how we find a model's final prediction

scores = torch.tensor([
    [10., 0., 5., 20., 1.],
    [1., 30., 2., 5., 0.]])

best_indices = torch.argmax(scores, dim=1)

print(f'Best indices for each row: {best_indices}')

Best indices for each row: tensor([3, 1])


In [ ]:
# torch.gather: specific indexing

data = torch.tensor([
    [10, 11, 12, 13],
    [20, 21, 22, 23],
    [30, 31, 32, 33]
    ])

